config/routes.rb
Recipe::Application.routes.draw do
  resources :dishes do
	resources :comments
  end
  resources :users
  resource :session
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  get "dishes/index"

  

  root :to => 'dishes#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :dish
	
	validates :name, :email, :body, :presence => true
	

end

app/models/dish.rb
class Dish < ActiveRecord::Base
	validates :title, :presence => true, :length => { :maximum => 150}
	validates :ingredients, :presence => true
	validates :direction, :presence => true
	validates_numericality_of :duration, :presence => true, :greater_than => 0
	validates_attachment_content_type :avatar, :content_type => 'image/jpeg'
	validates_attachment_presence :avatar



	belongs_to :user
	has_many :comments
	
	# added to upload image
	# has_attached_file :avatar, :styles => {:url => "25x25#", :thumb => "100x100#",   :small => "150x150>",   :large => "400x400>" } 
	# has_attached_file :avatar , :styles => { :thumb=> "100x100#", :small  => "150x150>" }
	# has_attached_file :avatar , :styles => { :normal => "100x100#", :small => ["70x70>", :jpg] }
	has_attached_file :avatar , :styles => { :thumb=> "100x100#", :small  => "150x150>", :medium => "300x300>", :large =>   "400x400>" }

	CATEGORY1_TYPES = ["Chicken", "Beef", "Pork", "Vegetable", "Seafood", "Veal", "Bakery Goods", "Others"]
	CATEGORY2_TYPES = ["Breakfast", "Main Course", "Side Dish", "Soup", "Salad", "Burger & Sandwich", "Pasta", "Snack", "Dessert", "Others"]
	CATEGORY3_TYPES = ["American", "Vietnamese", "Chinese", "German", "Japanese", "Indian", "Mexican", "European", "Filipino", "Others", "unknown"]

	def owned_by?(owner)
		return false unless owner.is_a? User
		user == owner
	end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
	attr_accessor :password
	
	validates :email, :uniqueness => true, :length => {:within => 5..50},
			:format => {:with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i}
		
	validates :password, :confirmation => true,
		:length => {:within => 4..20},
		:presence => true,
		:if => :password_required?

	has_one :profile
	has_many :dishes, :order => 'title ASC',
		:dependent => :nullify
	has_many :replies, :through => :dishes, :source => :comments
	
	before_save :encrypt_new_password
	
	def self.authenticate(email, password)
		user = find_by_email(email)
		return user if user && user.authenticated?(password)
	end
	def authenticated?(password)
		self.hashed_password == encrypt(password)
	end
	
	protected
		def encrypt_new_password
			return if password.blank?
			self.hashed_password = encrypt(password)
		end
	
	def password_required?
		hashed_password.blank? || password.present?
	end
	def encrypt(string)
		Digest::SHA1.hexdigest(string)
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base  
protect_from_forgery  

protected     
	# Returns the currently logged in user or nil if there isn't one    
	def current_user      
		return unless session[:user_id]      
		@current_user ||= User.find_by_id(session[:user_id])     
	end
	
	# Make current_user available in templates as a helper    
	helper_method :current_user    
	
	# Filter method to enforce a login requirement    
	# Apply as a before_filter on any controller you want to protect    
	def authenticate      
		logged_in? ? true : access_denied   
	end    
	
	# Predicate method to test for a logged in user        
	def logged_in?      
		current_user.is_a? User    
	end    
	
	# Make logged_in? available in templates as a helper    
	helper_method :logged_in?    
	
	def access_denied      
		redirect_to login_path, :notice => "Please log in to continue" and return false    
	end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController  
before_filter :load_dish
#, :except => :destroy
#before_filter :authenticate, :only => :destroy

def create    
	@comment = @dish.comments.new(params[:comment])    
	if @comment.save      
		redirect_to @dish, :notice => 'Thanks for your comment'    
	else      
		redirect_to @dish, :alert => 'Unable to add comment'    
	end  
end    

def destroy    
	#@dish = current_user.dishes.find(params[:dish_id])
	@comment = @dish.comments.find(params[:id])    
	@comment.destroy    
	redirect_to @dish, :notice => 'Comment deleted'  
end    

private    
	def load_dish     
		@dish = Dish.find(params[:dish_id])    
	end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  # GET /dishes
  # GET /dishes.xml
  before_filter :authenticate, :except => [:index, :show]
  
  def index
    #@dishes = Dish.all
	@dishes = Dish.paginate :page=>params[:page], :order => 'title', :per_page => 4

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dishes }
    end
  end

  # GET /dishes/1
  # GET /dishes/1.xml
  def show
    @dish = Dish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dish }
    end
  end

  # GET /dishes/new
  # GET /dishes/new.xml
  def new
    @dish = Dish.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dish }
    end
  end

  # GET /dishes/1/edit
  def edit
    #@dish = Dish.find(params[:id])
	@dish = current_user.dishes.find(params[:id])
  end

  # POST /dishes
  # POST /dishes.xml
  def create
    #@dish = Dish.new(params[:dish])
	@dish = current_user.dishes.new(params[:dish])
    respond_to do |format|
      if @dish.save
        format.html { redirect_to(@dish, :notice => 'Dish was successfully created.') }
        format.xml  { render :xml => @dish, :status => :created, :location => @dish }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dish.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dishes/1
  # PUT /dishes/1.xml
  def update
    #@dish = Dish.find(params[:id])
	@dish = current_user.dishes.find(params[:id])
    respond_to do |format|
      if @dish.update_attributes(params[:dish])
        format.html { redirect_to(@dish, :notice => 'Dish was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dish.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.xml
  def destroy
    #@dish = Dish.find(params[:id])
	@dish = current_user.dishes.find(params[:id])
    @dish.destroy

    respond_to do |format|
      format.html { redirect_to(dishes_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create    
	if user = User.authenticate(params[:email], params[:password])      
		session[:user_id] = user.id      
		redirect_to root_path, :notice => "Logged in successfully"    
	else      
		flash.now[:alert] = "Invalid login/password combination"      
		render :action => 'new'    
	end  
  end
  
  def destroy
	reset_session
	redirect_to root_path :notice => "You successfully logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate, :only => [:edit, :update]

	def new
		@user = User.new
	end
	def create
		@user = User.new(params[:user])
		if @user.save
			redirect_to dishes_path, :notice => 'User successfully added.'
		else
			render :action => 'new'
		end
	end
	def edit
		#@user = User.find(params[:id])
		@user = current_user
	end
	def update
		#@user = User.find(params[:id])
		@user = current_user
		if @user.update_attributes(params[:user])
			redirect_to dishes_path, :notice => 'Updated user information successfully.'
		else
			render :action => 'edit'
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def submit_or_cancel(form, name='Cancel')
		form.submit + " or " +
			link_to(name, 'javascript:history.go(-1);', :class => 'cancel')
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>  
    <p>
	<%= comment.name %> &lt;<%= comment.email %>&gt; said:    
	<% if @dish.owned_by? current_user %>
		<%= comment.body %>
		<span class='actions'>      
			<%= link_to 'Delete', [@dish, comment], :confirm => 'Are you sure?', :method => :delete %>    
		</span>
	<% end %>
	</p>
<% end %>

app/views/comments/new.html.erb
<%= form_for([@dish, @dish.comments.new]) do |f| %>  
	<div class="field">    
		<%= f.label :name %><br />    
		<%= f.text_field :name %>  
	</div>  
	<div class="field">    
		<%= f.label :email %><br />    
		<%= f.text_field :email %>  
	</div>  
	<div class="field">    
		<%= f.label :body %><br />    
		<%= f.text_area :body %>  
	</div>  
	<div class="actions">    
		<%= f.submit 'Add' %>  
	</div>
<% end %>

app/views/dishes/_dish.html.erb
<%= div_for dish do %>  
<h3>    
	<%= link_to dish.title, dish %>    
	<% if dish.owned_by? current_user %>
		<span class='actions'>      
			<%= link_to "Edit", edit_dish_path(dish) %>     
			<%= link_to "Delete", dish, :confirm => "Are you sure?", :method => :delete %>
		</span>  
	<% end %>
</h3>  
<div id="dishes">
<%= dish.category1%>, <%= dish.category2 %>, <%= dish.category3 %> <br/>
Ingredients: <%= simple_format dish.ingredients %> 
Cooking Duration (min): <%= dish.duration %> <br/>

<% if dish.avatar.exists? then %>
	<p><%= image_tag dish.avatar.url(:medium) %> </p>
<% else %>
	<p> There are no photo's attached, upload one. </p>
<% end %>

</div>
<% end %>

app/views/dishes/_form.html.erb
<%= form_for(@dish, :html => { :multipart => true}) do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :class => 'title' %>
  </div>
  <div class="field">
    <%= label_tag "Category 1" %><br />
    <%= f.select :category1, Dish::CATEGORY1_TYPES,
		:prompt => 'Choose a value' %>
  </div>
  <div class="field">
    <%= label_tag "Category 2" %><br />
    <%= f.select :category2, Dish::CATEGORY2_TYPES,
		:prompt => 'Choose a value' %>
  </div>
  <div class="field">
    <%= label_tag  "Category 3" %><br />
    <%= f.select :category3, Dish::CATEGORY3_TYPES,
		:prompt => 'Choose a value' %>
  </div>
  <div class="field">
    <%= label_tag "Cooking Duration (min)" %><br />
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
    <%= label_tag "Kid's Menu" %>
    <%= f.check_box :kidsMenu %><br />
  </div>
  <div class="field">
    <%= f.label "Gluten Free" %>
    <%= f.check_box :glutenFree %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br />
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :direction %><br />
    <%= f.text_area :direction %>
  </div>
  <div class="field">
    <%= label_tag "Comment" %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%# <%= f.submit %> 
	<%= submit_or_cancel(f) %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form' %>

app/views/dishes/index.html.erb
<h1>Listing Dishes</h1>

<div id="dishes">
	<%= render @dishes %>
</div>

<p><%= will_paginate @dishes %></p>

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form' %>

app/views/dishes/show.html - Copy.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @dish.title %>
</p>

<p>
  <b>Category1:</b>
  <%= @dish.category1 %>
</p>

<p>
  <b>Category2:</b>
  <%= @dish.category2 %>
</p>

<p>
  <b>Category3:</b>
  <%= @dish.category3 %>
</p>

<p>
  <b>Duration:</b>
  <%= @dish.duration %>
</p>

<p>
  <b>Image url:</b>
  <%= @dish.image_url %>
</p>

<p>
  <b>Kidsmenu:</b>
  <%= @dish.kidsMenu %>
</p>

<p>
  <b>Glutenfree:</b>
  <%= @dish.glutenFree %>
</p>

<p>
  <b>Ingredients:</b>
  <%= @dish.ingredients %>
</p>

<p>
  <b>Direction:</b>
  <%= @dish.direction %>
</p>

<p>
  <b>Comment:</b>
  <%= @dish.description %>
</p>

<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<%= render @dish %>

<h3>Comments</h3>
<div id="comments">
	<%= render @dish.comments %>
</div>

<%= render :file => 'comments/new' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipe</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div id="header">
		<h1><%= link_to "Recipe", root_path %></h1>
		<div id="user_bar">
			<% if logged_in? %>
				<%= link_to "New Dish", new_dish_path %> |
				<%= link_to "Edit Password", edit_user_path(current_user) %> |
				<%= link_to "Logout", logout_path %>
			<% else %>
				<%= link_to "Login", login_path %>
			<% end %>
		</div>
	</div>
	<div id="main">
		<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
		<%= content_tag :p, alert, :class => 'alert' if alert.present? %>
		<%= yield %>
	</div>
	<div id="footer">
		A simple recipe blog built for the chef in us.
	</div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>  
	<% if @user.errors.any? %>  
		<div id="errorExplanation">    
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>    
			<ul>    
				<% @user.errors.full_messages.each do |msg| %>      
					<li><%= msg %></li>    
				<% end %>    
			</ul>  
		</div>  
	<% end %>  
	<div class="field">    
		<%= f.label :email %><br />    
		<%= f.text_field :email %>  
	</div>  
	<div class="field">    
		<%= f.label :password %><br />    
		<%= f.password_field :password %>  
	</div>  
	<div class="field">    
		<%= f.label :password_confirmation %><br />    
		<%= f.password_field :password_confirmation %>  
	</div>  
	<div class="actions">    
		<%# <%= f.submit %> 
		<%= submit_or_cancel(f) %>
	</div>
<% end %> 

app/views/users/edit.html.erb
<h1>Editing User</h1>
<%= render 'form' %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render 'form' %>